import { useState } from 'react'
import type { ActivityType, Complexity, ResourceBand } from '../domain'
import { Heading, Modal, Panel, Pill } from '../components/ui'
import type { PageProps } from './types'

export function BaselinesPage({ store }: PageProps) {
  const [showForm, setShowForm] = useState(false)
  function save(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const now = new Date().toISOString()
    store.update((draft) => { draft.baselines.push({ id: crypto.randomUUID(), activityType: data.get('type') as ActivityType, band: data.get('band') as ResourceBand, complexity: data.get('complexity') as Complexity, hours: Number(data.get('hours')), effectiveFrom: String(data.get('effectiveFrom')), active: true, reason: String(data.get('reason')), version: Math.max(0, ...draft.baselines.map((item) => item.version)) + 1 }); draft.audits.unshift({ id: crypto.randomUUID(), timestamp: now, actor: 'u-owner', action: 'Create', entity: 'Baseline', entityId: 'new', detail: String(data.get('reason')) }); return draft }); setShowForm(false)
  }
  return <section className="content"><Heading eyebrow="ESTIMATION GOVERNANCE" title="Effort baselines" detail="Editable reference hours. Variance beyond ±25% is flagged, never blocked." action={<button className="primary" onClick={() => setShowForm(true)}>＋ New baseline</button>} /><Panel className="table-panel"><table><thead><tr><th>Activity type</th><th>Band</th><th>Complexity</th><th>Hours</th><th>Effective from</th><th>Version</th><th>Status</th><th>Reason</th></tr></thead><tbody>{store.state.baselines.map((baseline) => <tr key={baseline.id}><td><strong>{baseline.activityType}</strong></td><td>{baseline.band}</td><td>{baseline.complexity}</td><td><strong>{baseline.hours}h</strong></td><td>{baseline.effectiveFrom}</td><td>v{baseline.version}</td><td><Pill tone={baseline.active ? 'open' : 'neutral'}>{baseline.active ? 'Active' : 'Inactive'}</Pill></td><td>{baseline.reason}</td></tr>)}</tbody></table></Panel>{showForm && <Modal eyebrow="CONTROLLED CHANGE" title="Add baseline" onClose={() => setShowForm(false)}><form onSubmit={save}><div className="form-row"><label>Activity type<select name="type">{['Release','Project','BAU','Improvement','Learning','Other'].map(x => <option key={x}>{x}</option>)}</select></label><label>Resource band<select name="band">{['Junior','Senior','Not Applicable'].map(x => <option key={x}>{x}</option>)}</select></label></div><div className="form-row"><label>Complexity<select name="complexity">{['Low','Medium','High'].map(x => <option key={x}>{x}</option>)}</select></label><label>Baseline hours<input required name="hours" type="number" min="0" step="0.5" /></label></div><label>Effective from<input required name="effectiveFrom" type="date" /></label><label>Change reason<textarea required name="reason" /></label><div className="modal-actions"><button type="button" className="ghost" onClick={() => setShowForm(false)}>Cancel</button><button className="primary">Save baseline</button></div></form></Modal>}</section>
}
