import { useState } from 'react'
import { downloadTemplateCsv } from '../download'
import type { Activity, MonthlyEffort } from '../domain'
import { Heading, Panel, Pill } from '../components/ui'
import type { PageProps } from './types'

type Preview = { name: string; type: string; owner: string; resource: string; status: string; start: string; end: string; band: string; complexity: string; month: string; plan: string; actual: string; notes: string }
const splitCsv = (line: string) => line.match(/("[^"]*(?:""[^"]*)*"|[^,]*)(?:,|$)/g)?.map((value) => value.replace(/,$/, '').replace(/^"|"$/g, '').replaceAll('""', '"')) ?? []

export function MigrationPage({ store }: PageProps) {
  const [preview, setPreview] = useState<Preview[]>([])
  const [message, setMessage] = useState('')
  async function read(file?: File) {
    if (!file) return; const lines = (await file.text()).split(/\r?\n/).filter(Boolean); const rows = lines.slice(1).map(splitCsv)
    setPreview(rows.map((r) => ({ name:r[0]||'', type:r[1]||'Other', owner:r[2]||'', resource:r[3]||'', status:r[4]||'Not Started', start:r[5]||'', end:r[6]||'', band:r[7]||'Not Applicable', complexity:r[8]||'Low', month:r[9]||'', plan:r[10]||'', actual:r[11]||'', notes:r[12]||'' }))); setMessage('')
  }
  function importRows() {
    let count = 0
    store.update((draft) => { preview.filter((r) => r.name && /^\d{4}-\d{2}$/.test(r.month)).forEach((r) => { const id = crypto.randomUUID(); const owner = draft.people.find((p) => p.name.toLowerCase() === r.owner.toLowerCase())?.id ?? 'u-owner'; const resource = draft.people.find((p) => p.name.toLowerCase() === r.resource.toLowerCase())?.id; const activity: Activity = { id, name:r.name, type: (['Project','Release','BAU','Improvement','Learning','Other'].includes(r.type) ? r.type : 'Other') as Activity['type'], processOwnerId:owner, resourceId:resource, status:(['Not Started','In Progress','On Track','At Risk','Completed','On Hold'].includes(r.status) ? r.status : 'Not Started') as Activity['status'], startDate:r.start, endDate:r.end, band:(['Junior','Senior','Not Applicable'].includes(r.band) ? r.band : 'Not Applicable') as Activity['band'], complexity:(['Low','Medium','High'].includes(r.complexity) ? r.complexity : 'Low') as Activity['complexity'], source:'Migration', createdAt:new Date().toISOString(), createdBy:'u-owner' }; const effort: MonthlyEffort = { id:crypto.randomUUID(), activityId:id, month:r.month, classification:'Planned', plannedHours:r.plan ? Number(r.plan) : null, actualHours:r.actual ? Number(r.actual) : null, baselineHours:null, notes:r.notes, learnings:'', struggles:'', updatedAt:new Date().toISOString(), updatedBy:'u-owner' }; draft.activities.push(activity); draft.efforts.push(effort); count++ }); draft.audits.unshift({ id:crypto.randomUUID(), timestamp:new Date().toISOString(), actor:'u-owner', action:'Import', entity:'Migration', entityId:'csv', detail:`Imported ${count} rows` }); return draft }); setMessage(`${count} rows imported into the local development store.`); setPreview([])
  }
  return <section className="content"><Heading eyebrow="CONTROLLED ONBOARDING" title="Migration" detail="Stage and validate historical records before the SharePoint production import." action={<button className="ghost" onClick={downloadTemplateCsv}>Download CSV template</button>} /><div className="migration-steps"><Panel><span className="step">1</span><h3>Prepare</h3><p>Export the workbook source tab and align it to the template. The target mapping is based on P&amp;S - Effort per Month.</p></Panel><Panel><span className="step">2</span><h3>Validate</h3><p>Preview invalid dates, month keys, people and master values before writing records.</p></Panel><Panel><span className="step">3</span><h3>Import</h3><p>Production will use a staged flow with duplicate detection, audit evidence and rollback.</p></Panel></div><Panel className="upload-zone"><input id="migration-file" type="file" accept=".csv,text/csv" onChange={(event) => read(event.target.files?.[0])} /><label htmlFor="migration-file"><strong>Choose migration CSV</strong><span>CSV preview stays on this computer in the MVP adapter.</span></label></Panel>{message && <div className="notice success">{message}</div>}{preview.length > 0 && <Panel className="table-panel"><div className="panel-heading"><div><h2>Validation preview</h2><p className="muted">{preview.length} source rows</p></div><button className="primary" onClick={importRows}>Import valid rows</button></div><table><thead><tr><th>Activity</th><th>Type</th><th>Month</th><th>Plan</th><th>Actual</th><th>Validation</th></tr></thead><tbody>{preview.slice(0,50).map((r,i) => { const valid = Boolean(r.name && /^\d{4}-\d{2}$/.test(r.month)); return <tr key={i}><td>{r.name || 'Missing name'}</td><td>{r.type}</td><td>{r.month || 'Missing'}</td><td>{r.plan || '—'}</td><td>{r.actual || '—'}</td><td><Pill tone={valid ? 'open' : 'danger'}>{valid ? 'Ready' : 'Fix row'}</Pill></td></tr> })}</tbody></table></Panel>}</section>
}
