import { useState } from 'react'
import { Heading, Modal, Panel, Pill } from '../components/ui'
import type { PageProps } from './types'

export function ReleasesPage({ store }: PageProps) {
  const [showForm, setShowForm] = useState(false)
  function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); store.update((draft) => { draft.releases.push({ id: crypto.randomUUID(), releaseName: String(d.get('name')), releaseType: String(d.get('type')), sourceSystem: d.get('source') as 'TFS'|'Windchill'|'Manual', plannedClosure: String(d.get('planned')), actualClosure: String(d.get('actual')) || undefined, milestone: String(d.get('milestone')), featureCount: Number(d.get('features')), bugCount: Number(d.get('bugs')), uploadedAt: new Date().toISOString() }); return draft }); setShowForm(false) }
  return <section className="content"><Heading eyebrow="RELEASE INTELLIGENCE" title="Release milestones" detail="Combine TFS, Windchill and manual records for closure trends and complexity." action={<button className="primary" onClick={() => setShowForm(true)}>＋ Add release</button>} /><div className="metric-grid compact"><article><span>Releases</span><strong>{store.state.releases.length}</strong></article><article><span>Closed</span><strong>{store.state.releases.filter(x => x.actualClosure).length}</strong></article><article><span>Late closures</span><strong>{store.state.releases.filter(x => x.actualClosure && x.actualClosure > x.plannedClosure).length}</strong></article><article><span>Bugs / Features</span><strong>{store.state.releases.reduce((s,x)=>s+x.bugCount,0)} / {store.state.releases.reduce((s,x)=>s+x.featureCount,0)}</strong></article></div><Panel className="table-panel"><table><thead><tr><th>Release</th><th>Type / Source</th><th>Milestone</th><th>Planned</th><th>Actual</th><th>Complexity inputs</th><th>Closure</th></tr></thead><tbody>{store.state.releases.map(x => <tr key={x.id}><td><strong>{x.releaseName}</strong></td><td>{x.releaseType}<small>{x.sourceSystem}</small></td><td>{x.milestone}</td><td>{x.plannedClosure}</td><td>{x.actualClosure ?? 'Open'}</td><td>{x.featureCount} features<small>{x.bugCount} bugs</small></td><td><Pill tone={!x.actualClosure ? 'neutral' : x.actualClosure > x.plannedClosure ? 'warning' : 'open'}>{!x.actualClosure ? 'Open' : x.actualClosure > x.plannedClosure ? 'Late' : 'On time'}</Pill></td></tr>)}</tbody></table></Panel>{showForm && <Modal eyebrow="RELEASE DATA" title="Add milestone" onClose={() => setShowForm(false)}><form onSubmit={save}><label>Release name<input name="name" required /></label><div className="form-row"><label>Release type<select name="type">{store.state.masters.filter(x => x.type === 'Release Type' && x.active).map(x => <option key={x.id}>{x.value}</option>)}</select></label><label>Source<select name="source"><option>TFS</option><option>Windchill</option><option>Manual</option></select></label></div><label>Milestone<input name="milestone" required /></label><div className="form-row"><label>Planned closure<input name="planned" type="date" required /></label><label>Actual closure<input name="actual" type="date" /></label></div><div className="form-row"><label>Features<input name="features" type="number" min="0" defaultValue="0" /></label><label>Bugs<input name="bugs" type="number" min="0" defaultValue="0" /></label></div><div className="modal-actions"><button type="button" className="ghost" onClick={() => setShowForm(false)}>Cancel</button><button className="primary">Add milestone</button></div></form></Modal>}</section>
}
